package servicioclientes.externalservices.web.corebanking.denarius;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-08-04T10:22:02.141-05:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", name = "IServiciosClientes")
@XmlSeeAlso({servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.ObjectFactory.class, servicioclientes.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.ObjectFactory.class})
public interface IServiciosClientes {

    @WebMethod(operationName = "RegistrarRelacion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarRelacion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarRelacion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarRelacionResponse")
    @RequestWrapper(localName = "RegistrarRelacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.RegistrarRelacion")
    @ResponseWrapper(localName = "RegistrarRelacionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.RegistrarRelacionResponse")
    @WebResult(name = "RegistrarRelacionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase registrarRelacion(

        @WebParam(name = "meRelacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MERelacionCliente meRelacion
    );

    @WebMethod(operationName = "CrearClienteResumido", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteResumido")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteResumido", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteResumidoResponse")
    @RequestWrapper(localName = "CrearClienteResumido", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearClienteResumido")
    @ResponseWrapper(localName = "CrearClienteResumidoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearClienteResumidoResponse")
    @WebResult(name = "CrearClienteResumidoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSCreacionCliente crearClienteResumido(

        @WebParam(name = "meCreacionClienteResumido", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MECreacionClienteResumido meCreacionClienteResumido
    );

    @WebMethod(operationName = "CrearNuevoCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearNuevoCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearNuevoCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearNuevoClienteResponse")
    @RequestWrapper(localName = "CrearNuevoCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearNuevoCliente")
    @ResponseWrapper(localName = "CrearNuevoClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearNuevoClienteResponse")
    @WebResult(name = "CrearNuevoClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSCreacionCliente crearNuevoCliente(

        @WebParam(name = "meCreacionClientes", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MECreacionCliente meCreacionClientes
    );

    @WebMethod(operationName = "GuardarRubrosEmpleo", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarRubrosEmpleo")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarRubrosEmpleo", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarRubrosEmpleoResponse")
    @RequestWrapper(localName = "GuardarRubrosEmpleo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GuardarRubrosEmpleo")
    @ResponseWrapper(localName = "GuardarRubrosEmpleoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GuardarRubrosEmpleoResponse")
    @WebResult(name = "GuardarRubrosEmpleoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase guardarRubrosEmpleo(

        @WebParam(name = "meRubroEmpleo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MERubroEmpleo meRubroEmpleo
    );

    @WebMethod(operationName = "ActualizarClienteDefinitivo", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarClienteDefinitivo")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarClienteDefinitivo", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarClienteDefinitivoResponse")
    @RequestWrapper(localName = "ActualizarClienteDefinitivo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarClienteDefinitivo")
    @ResponseWrapper(localName = "ActualizarClienteDefinitivoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarClienteDefinitivoResponse")
    @WebResult(name = "ActualizarClienteDefinitivoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarClienteDefinitivo(

        @WebParam(name = "meActualizacionCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MeDatosCliente meActualizacionCliente
    );

    @WebMethod(operationName = "ActualizarInformacionCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarInformacionCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarInformacionCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarInformacionClienteResponse")
    @RequestWrapper(localName = "ActualizarInformacionCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarInformacionCliente")
    @ResponseWrapper(localName = "ActualizarInformacionClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarInformacionClienteResponse")
    @WebResult(name = "ActualizarInformacionClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarInformacionCliente(

        @WebParam(name = "meDatosCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MeDatosCliente meDatosCliente
    );

    @WebMethod(operationName = "RegistrarAccionistaAdministrador", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarAccionistaAdministrador")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarAccionistaAdministrador", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarAccionistaAdministradorResponse")
    @RequestWrapper(localName = "RegistrarAccionistaAdministrador", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.RegistrarAccionistaAdministrador")
    @ResponseWrapper(localName = "RegistrarAccionistaAdministradorResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.RegistrarAccionistaAdministradorResponse")
    @WebResult(name = "RegistrarAccionistaAdministradorResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase registrarAccionistaAdministrador(

        @WebParam(name = "meAccionistaAdministrador", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEAccionistaAdministrador meAccionistaAdministrador
    );

    @WebMethod(operationName = "EliminarEmpleo", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarEmpleo")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarEmpleo", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarEmpleoResponse")
    @RequestWrapper(localName = "EliminarEmpleo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EliminarEmpleo")
    @ResponseWrapper(localName = "EliminarEmpleoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EliminarEmpleoResponse")
    @WebResult(name = "EliminarEmpleoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase eliminarEmpleo(

        @WebParam(name = "meEmpleo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEEmpleo meEmpleo
    );

    @WebMethod(operationName = "ActualizarInformaciónVinculado", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarInformaciónVinculado")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarInformaciónVinculado", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarInformaciónVinculadoResponse")
    @RequestWrapper(localName = "ActualizarInformaciónVinculado", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarInformaciónVinculado")
    @ResponseWrapper(localName = "ActualizarInformaciónVinculadoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarInformaciónVinculadoResponse")
    @WebResult(name = "ActualizarInformaciónVinculadoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSVinculado actualizarInformaciónVinculado(

        @WebParam(name = "meVinculado", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEVinculado meVinculado
    );

    @WebMethod(operationName = "CrearClienteConsolidado", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteConsolidado")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteConsolidado", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteConsolidadoResponse")
    @RequestWrapper(localName = "CrearClienteConsolidado", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearClienteConsolidado")
    @ResponseWrapper(localName = "CrearClienteConsolidadoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearClienteConsolidadoResponse")
    @WebResult(name = "CrearClienteConsolidadoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSCreacionCliente crearClienteConsolidado(

        @WebParam(name = "meCreacionClientes", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MECreacionCliente meCreacionClientes
    );

    @WebMethod(operationName = "ConsultarClientesCondiciones", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarClientesCondiciones")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarClientesCondiciones", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarClientesCondicionesResponse")
    @RequestWrapper(localName = "ConsultarClientesCondiciones", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarClientesCondiciones")
    @ResponseWrapper(localName = "ConsultarClientesCondicionesResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarClientesCondicionesResponse")
    @WebResult(name = "ConsultarClientesCondicionesResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaClientesCondiciones consultarClientesCondiciones(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultaClientesCondiciones meConsulta
    );

    @WebMethod(operationName = "GenerarCertificadoRelacionesComerciales", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GenerarCertificadoRelacionesComerciales")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GenerarCertificadoRelacionesComerciales", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GenerarCertificadoRelacionesComercialesResponse")
    @RequestWrapper(localName = "GenerarCertificadoRelacionesComerciales", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GenerarCertificadoRelacionesComerciales")
    @ResponseWrapper(localName = "GenerarCertificadoRelacionesComercialesResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GenerarCertificadoRelacionesComercialesResponse")
    @WebResult(name = "GenerarCertificadoRelacionesComercialesResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase generarCertificadoRelacionesComerciales(

        @WebParam(name = "meCertificado", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MECertificadoRelacionesComerciales meCertificado
    );

    @WebMethod(operationName = "ConsultarFuncionario", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarFuncionario")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarFuncionario", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarFuncionarioResponse")
    @RequestWrapper(localName = "ConsultarFuncionario", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarFuncionario")
    @ResponseWrapper(localName = "ConsultarFuncionarioResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarFuncionarioResponse")
    @WebResult(name = "ConsultarFuncionarioResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSFuncionario consultarFuncionario(

        @WebParam(name = "meConsultaFuncionario", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultasCliente meConsultaFuncionario
    );

    @WebMethod(operationName = "ConsultarInformaciónVinculado", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarInformaciónVinculado")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarInformaciónVinculado", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarInformaciónVinculadoResponse")
    @RequestWrapper(localName = "ConsultarInformaciónVinculado", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarInformaciónVinculado")
    @ResponseWrapper(localName = "ConsultarInformaciónVinculadoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarInformaciónVinculadoResponse")
    @WebResult(name = "ConsultarInformaciónVinculadoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSVinculado consultarInformaciónVinculado(

        @WebParam(name = "meConsultaVinculado", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultasCliente meConsultaVinculado
    );

    @WebMethod(operationName = "ActualizarRelacion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarRelacion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarRelacion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarRelacionResponse")
    @RequestWrapper(localName = "ActualizarRelacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarRelacion")
    @ResponseWrapper(localName = "ActualizarRelacionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarRelacionResponse")
    @WebResult(name = "ActualizarRelacionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarRelacion(

        @WebParam(name = "meRelacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MERelacionCliente meRelacion
    );

    @WebMethod(operationName = "ValidarCertificadoRelacionesComerciales", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarCertificadoRelacionesComerciales")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarCertificadoRelacionesComerciales", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarCertificadoRelacionesComercialesResponse")
    @RequestWrapper(localName = "ValidarCertificadoRelacionesComerciales", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ValidarCertificadoRelacionesComerciales")
    @ResponseWrapper(localName = "ValidarCertificadoRelacionesComercialesResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ValidarCertificadoRelacionesComercialesResponse")
    @WebResult(name = "ValidarCertificadoRelacionesComercialesResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase validarCertificadoRelacionesComerciales(

        @WebParam(name = "meCertificado", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MECertificadoRelacionesComerciales meCertificado
    );

    @WebMethod(operationName = "ConsultarClientePorIdentificacion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarClientePorIdentificacion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarClientePorIdentificacion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarClientePorIdentificacionResponse")
    @RequestWrapper(localName = "ConsultarClientePorIdentificacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarClientePorIdentificacion")
    @ResponseWrapper(localName = "ConsultarClientePorIdentificacionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarClientePorIdentificacionResponse")
    @WebResult(name = "ConsultarClientePorIdentificacionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSClientes consultarClientePorIdentificacion(

        @WebParam(name = "meConsultasClientes", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MEIdentificacionCliente meConsultasClientes
    );

    @WebMethod(operationName = "GuardarDatosEspecificosCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarDatosEspecificosCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarDatosEspecificosCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarDatosEspecificosClienteResponse")
    @RequestWrapper(localName = "GuardarDatosEspecificosCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GuardarDatosEspecificosCliente")
    @ResponseWrapper(localName = "GuardarDatosEspecificosClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GuardarDatosEspecificosClienteResponse")
    @WebResult(name = "GuardarDatosEspecificosClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase guardarDatosEspecificosCliente(

        @WebParam(name = "meEntrada", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEDatosEspecificosCliente meEntrada
    );

    @WebMethod(operationName = "SincronizarDatosContactabilidad", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/SincronizarDatosContactabilidad")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/SincronizarDatosContactabilidad", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/SincronizarDatosContactabilidadResponse")
    @RequestWrapper(localName = "SincronizarDatosContactabilidad", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.SincronizarDatosContactabilidad")
    @ResponseWrapper(localName = "SincronizarDatosContactabilidadResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.SincronizarDatosContactabilidadResponse")
    @WebResult(name = "SincronizarDatosContactabilidadResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase sincronizarDatosContactabilidad(

        @WebParam(name = "meBase", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeEntradaBase meBase
    );

    @WebMethod(operationName = "ConsultarRepresentanteLegal", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarRepresentanteLegal")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarRepresentanteLegal", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarRepresentanteLegalResponse")
    @RequestWrapper(localName = "ConsultarRepresentanteLegal", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarRepresentanteLegal")
    @ResponseWrapper(localName = "ConsultarRepresentanteLegalResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarRepresentanteLegalResponse")
    @WebResult(name = "ConsultarRepresentanteLegalResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaRepresentanteLegal consultarRepresentanteLegal(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MEIdentificacionCliente meConsulta
    );

    @WebMethod(operationName = "ConsultarRefenciasPersonales", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarRefenciasPersonales")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarRefenciasPersonales", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarRefenciasPersonalesResponse")
    @RequestWrapper(localName = "ConsultarRefenciasPersonales", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarRefenciasPersonales")
    @ResponseWrapper(localName = "ConsultarRefenciasPersonalesResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarRefenciasPersonalesResponse")
    @WebResult(name = "ConsultarRefenciasPersonalesResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaReferenciasPersonales consultarRefenciasPersonales(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MEIdentificacionCliente meConsulta
    );

    @WebMethod(operationName = "CrearEmpleo", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearEmpleo")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearEmpleo", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearEmpleoResponse")
    @RequestWrapper(localName = "CrearEmpleo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearEmpleo")
    @ResponseWrapper(localName = "CrearEmpleoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearEmpleoResponse")
    @WebResult(name = "CrearEmpleoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase crearEmpleo(

        @WebParam(name = "meEmpleo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEEmpleo meEmpleo
    );

    @WebMethod(operationName = "ActualizarDireccionCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarDireccionCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarDireccionCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarDireccionClienteResponse")
    @RequestWrapper(localName = "ActualizarDireccionCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarDireccionCliente")
    @ResponseWrapper(localName = "ActualizarDireccionClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarDireccionClienteResponse")
    @WebResult(name = "ActualizarDireccionClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarDireccionCliente(

        @WebParam(name = "meActualizacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEDireccion meActualizacion
    );

    @WebMethod(operationName = "RegistrarClienteBancaEnLinea", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarClienteBancaEnLinea")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarClienteBancaEnLinea", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarClienteBancaEnLineaResponse")
    @RequestWrapper(localName = "RegistrarClienteBancaEnLinea", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.RegistrarClienteBancaEnLinea")
    @ResponseWrapper(localName = "RegistrarClienteBancaEnLineaResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.RegistrarClienteBancaEnLineaResponse")
    @WebResult(name = "RegistrarClienteBancaEnLineaResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase registrarClienteBancaEnLinea(

        @WebParam(name = "meRegistro", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEIdentificacion meRegistro
    );

    @WebMethod(operationName = "ActualizarRelacionCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarRelacionCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarRelacionCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarRelacionClienteResponse")
    @RequestWrapper(localName = "ActualizarRelacionCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarRelacionCliente")
    @ResponseWrapper(localName = "ActualizarRelacionClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarRelacionClienteResponse")
    @WebResult(name = "ActualizarRelacionClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarRelacionCliente(

        @WebParam(name = "meActualizacionRelacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MERelacion meActualizacionRelacion
    );

    @WebMethod(operationName = "EliminarRelacion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarRelacion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarRelacion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarRelacionResponse")
    @RequestWrapper(localName = "EliminarRelacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EliminarRelacion")
    @ResponseWrapper(localName = "EliminarRelacionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EliminarRelacionResponse")
    @WebResult(name = "EliminarRelacionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase eliminarRelacion(

        @WebParam(name = "meRelacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MERelacionCliente meRelacion
    );

    @WebMethod(operationName = "GuardarPasivoEvaluacion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarPasivoEvaluacion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarPasivoEvaluacion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarPasivoEvaluacionResponse")
    @RequestWrapper(localName = "GuardarPasivoEvaluacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GuardarPasivoEvaluacion")
    @ResponseWrapper(localName = "GuardarPasivoEvaluacionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GuardarPasivoEvaluacionResponse")
    @WebResult(name = "GuardarPasivoEvaluacionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase guardarPasivoEvaluacion(

        @WebParam(name = "mePasivo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEPasivo mePasivo
    );

    @WebMethod(operationName = "ConsultarEmpleos", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarEmpleos")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarEmpleos", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarEmpleosResponse")
    @RequestWrapper(localName = "ConsultarEmpleos", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarEmpleos")
    @ResponseWrapper(localName = "ConsultarEmpleosResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarEmpleosResponse")
    @WebResult(name = "ConsultarEmpleosResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaEmpleo consultarEmpleos(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MEIdentificacionCliente meConsulta
    );

    @WebMethod(operationName = "ConsultarRelacionesClientePeps", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarRelacionesClientePeps")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarRelacionesClientePeps", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarRelacionesClientePepsResponse")
    @RequestWrapper(localName = "ConsultarRelacionesClientePeps", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarRelacionesClientePeps")
    @ResponseWrapper(localName = "ConsultarRelacionesClientePepsResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarRelacionesClientePepsResponse")
    @WebResult(name = "ConsultarRelacionesClientePepsResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaRelaciones consultarRelacionesClientePeps(

        @WebParam(name = "meConsultaPep", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultasCliente meConsultaPep
    );

    @WebMethod(operationName = "ActualizarFuncionario", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarFuncionario")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarFuncionario", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarFuncionarioResponse")
    @RequestWrapper(localName = "ActualizarFuncionario", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarFuncionario")
    @ResponseWrapper(localName = "ActualizarFuncionarioResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarFuncionarioResponse")
    @WebResult(name = "ActualizarFuncionarioResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSFuncionario actualizarFuncionario(

        @WebParam(name = "meFuncionario", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEFuncionario meFuncionario
    );

    @WebMethod(operationName = "ActualizarFechaNacimientoCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarFechaNacimientoCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarFechaNacimientoCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarFechaNacimientoClienteResponse")
    @RequestWrapper(localName = "ActualizarFechaNacimientoCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarFechaNacimientoCliente")
    @ResponseWrapper(localName = "ActualizarFechaNacimientoClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarFechaNacimientoClienteResponse")
    @WebResult(name = "ActualizarFechaNacimientoClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarFechaNacimientoCliente(

        @WebParam(name = "meDatosCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MeDatosCliente meDatosCliente
    );

    @WebMethod(operationName = "ConsultarParticipacionAccionariaYAdministradoresPeps", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarParticipacionAccionariaYAdministradoresPeps")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarParticipacionAccionariaYAdministradoresPeps", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarParticipacionAccionariaYAdministradoresPepsResponse")
    @RequestWrapper(localName = "ConsultarParticipacionAccionariaYAdministradoresPeps", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarParticipacionAccionariaYAdministradoresPeps")
    @ResponseWrapper(localName = "ConsultarParticipacionAccionariaYAdministradoresPepsResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarParticipacionAccionariaYAdministradoresPepsResponse")
    @WebResult(name = "ConsultarParticipacionAccionariaYAdministradoresPepsResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaParticipacionAccionaria consultarParticipacionAccionariaYAdministradoresPeps(

        @WebParam(name = "meConsultaParticipacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultasCliente meConsultaParticipacion
    );

    @WebMethod(operationName = "ActualizarEmpleo", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarEmpleo")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarEmpleo", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarEmpleoResponse")
    @RequestWrapper(localName = "ActualizarEmpleo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarEmpleo")
    @ResponseWrapper(localName = "ActualizarEmpleoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarEmpleoResponse")
    @WebResult(name = "ActualizarEmpleoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarEmpleo(

        @WebParam(name = "meEmpleo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEEmpleo meEmpleo
    );

    @WebMethod(operationName = "ConsultarEstadoSituacion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarEstadoSituacion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarEstadoSituacion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarEstadoSituacionResponse")
    @RequestWrapper(localName = "ConsultarEstadoSituacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarEstadoSituacion")
    @ResponseWrapper(localName = "ConsultarEstadoSituacionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarEstadoSituacionResponse")
    @WebResult(name = "ConsultarEstadoSituacionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSInformacionFinanciera consultarEstadoSituacion(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEIdentificacion meConsulta
    );

    @WebMethod(operationName = "InformacionFinancieraClientes", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/InformacionFinancieraClientes")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/InformacionFinancieraClientes", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/InformacionFinancieraClientesResponse")
    @RequestWrapper(localName = "InformacionFinancieraClientes", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.InformacionFinancieraClientes")
    @ResponseWrapper(localName = "InformacionFinancieraClientesResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.InformacionFinancieraClientesResponse")
    @WebResult(name = "InformacionFinancieraClientesResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaClientes informacionFinancieraClientes(

        @WebParam(name = "meConsultaCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEInformacionFinancieraCliente meConsultaCliente
    );

    @WebMethod(operationName = "CrearActivo", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearActivo")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearActivo", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearActivoResponse")
    @RequestWrapper(localName = "CrearActivo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearActivo")
    @ResponseWrapper(localName = "CrearActivoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearActivoResponse")
    @WebResult(name = "CrearActivoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase crearActivo(

        @WebParam(name = "meActivo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEActivo meActivo
    );

    @WebMethod(operationName = "ValidarBaseImpedidos", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarBaseImpedidos")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarBaseImpedidos", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarBaseImpedidosResponse")
    @RequestWrapper(localName = "ValidarBaseImpedidos", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ValidarBaseImpedidos")
    @ResponseWrapper(localName = "ValidarBaseImpedidosResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ValidarBaseImpedidosResponse")
    @WebResult(name = "ValidarBaseImpedidosResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase validarBaseImpedidos(

        @WebParam(name = "meValidarBaseImpedidos", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MEIdentificacionCliente meValidarBaseImpedidos
    );

    @WebMethod(operationName = "ValidarAprobacionMalasReferencias", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarAprobacionMalasReferencias")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarAprobacionMalasReferencias", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarAprobacionMalasReferenciasResponse")
    @RequestWrapper(localName = "ValidarAprobacionMalasReferencias", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ValidarAprobacionMalasReferencias")
    @ResponseWrapper(localName = "ValidarAprobacionMalasReferenciasResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ValidarAprobacionMalasReferenciasResponse")
    @WebResult(name = "ValidarAprobacionMalasReferenciasResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase validarAprobacionMalasReferencias(

        @WebParam(name = "meEntrada", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MEIdentificacionCliente meEntrada
    );

    @WebMethod(operationName = "ActualizarActivo", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarActivo")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarActivo", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarActivoResponse")
    @RequestWrapper(localName = "ActualizarActivo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarActivo")
    @ResponseWrapper(localName = "ActualizarActivoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarActivoResponse")
    @WebResult(name = "ActualizarActivoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarActivo(

        @WebParam(name = "meActivo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEActivo meActivo
    );

    @WebMethod(operationName = "CrearClienteProspecto", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteProspecto")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteProspecto", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteProspectoResponse")
    @RequestWrapper(localName = "CrearClienteProspecto", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearClienteProspecto")
    @ResponseWrapper(localName = "CrearClienteProspectoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearClienteProspectoResponse")
    @WebResult(name = "CrearClienteProspectoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSCreacionCliente crearClienteProspecto(

        @WebParam(name = "meCreacionClientes", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MECreacionCliente meCreacionClientes
    );

    @WebMethod(operationName = "ActualizarTelefonoCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarTelefonoCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarTelefonoCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarTelefonoClienteResponse")
    @RequestWrapper(localName = "ActualizarTelefonoCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarTelefonoCliente")
    @ResponseWrapper(localName = "ActualizarTelefonoClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarTelefonoClienteResponse")
    @WebResult(name = "ActualizarTelefonoClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarTelefonoCliente(

        @WebParam(name = "meCreacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.METelefono meCreacion
    );

    @WebMethod(operationName = "IniciarFlujoAprobacionRelacionadosPep", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/IniciarFlujoAprobacionRelacionadosPep")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/IniciarFlujoAprobacionRelacionadosPep", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/IniciarFlujoAprobacionRelacionadosPepResponse")
    @RequestWrapper(localName = "IniciarFlujoAprobacionRelacionadosPep", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.IniciarFlujoAprobacionRelacionadosPep")
    @ResponseWrapper(localName = "IniciarFlujoAprobacionRelacionadosPepResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.IniciarFlujoAprobacionRelacionadosPepResponse")
    @WebResult(name = "IniciarFlujoAprobacionRelacionadosPepResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase iniciarFlujoAprobacionRelacionadosPep(

        @WebParam(name = "meClientePep", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultasCliente meClientePep
    );

    @WebMethod(operationName = "ConsultarDatosCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarDatosCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarDatosCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarDatosClienteResponse")
    @RequestWrapper(localName = "ConsultarDatosCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarDatosCliente")
    @ResponseWrapper(localName = "ConsultarDatosClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarDatosClienteResponse")
    @WebResult(name = "ConsultarDatosClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultasCliente consultarDatosCliente(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultasCliente meConsulta
    );

    @WebMethod(operationName = "CrearTelefonoCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearTelefonoCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearTelefonoCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearTelefonoClienteResponse")
    @RequestWrapper(localName = "CrearTelefonoCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearTelefonoCliente")
    @ResponseWrapper(localName = "CrearTelefonoClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearTelefonoClienteResponse")
    @WebResult(name = "CrearTelefonoClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase crearTelefonoCliente(

        @WebParam(name = "meCreacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.METelefono meCreacion
    );

    @WebMethod(operationName = "ConsultaDatosCelular", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultaDatosCelular")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultaDatosCelular", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultaDatosCelularResponse")
    @RequestWrapper(localName = "ConsultaDatosCelular", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultaDatosCelular")
    @ResponseWrapper(localName = "ConsultaDatosCelularResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultaDatosCelularResponse")
    @WebResult(name = "ConsultaDatosCelularResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaCelular consultaDatosCelular(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultaCelular meConsulta
    );

    @WebMethod(operationName = "ConsultarDireccionesCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarDireccionesCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarDireccionesCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarDireccionesClienteResponse")
    @RequestWrapper(localName = "ConsultarDireccionesCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarDireccionesCliente")
    @ResponseWrapper(localName = "ConsultarDireccionesClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarDireccionesClienteResponse")
    @WebResult(name = "ConsultarDireccionesClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaDireccionesCliente consultarDireccionesCliente(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MEIdentificacionCliente meConsulta
    );

    @WebMethod(operationName = "ActualizarRefenciasPersonales", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarRefenciasPersonales")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarRefenciasPersonales", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarRefenciasPersonalesResponse")
    @RequestWrapper(localName = "ActualizarRefenciasPersonales", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarRefenciasPersonales")
    @ResponseWrapper(localName = "ActualizarRefenciasPersonalesResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarRefenciasPersonalesResponse")
    @WebResult(name = "ActualizarRefenciasPersonalesResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarRefenciasPersonales(

        @WebParam(name = "meReferenciaPersonal", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEReferenciasPersonales meReferenciaPersonal
    );

    @WebMethod(operationName = "ActualizarAccionistaAdministrador", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarAccionistaAdministrador")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarAccionistaAdministrador", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarAccionistaAdministradorResponse")
    @RequestWrapper(localName = "ActualizarAccionistaAdministrador", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarAccionistaAdministrador")
    @ResponseWrapper(localName = "ActualizarAccionistaAdministradorResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarAccionistaAdministradorResponse")
    @WebResult(name = "ActualizarAccionistaAdministradorResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarAccionistaAdministrador(

        @WebParam(name = "meAccionistaAdministrador", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEAccionistaAdministrador meAccionistaAdministrador
    );

    @WebMethod(operationName = "EliminarActivo", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarActivo")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarActivo", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarActivoResponse")
    @RequestWrapper(localName = "EliminarActivo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EliminarActivo")
    @ResponseWrapper(localName = "EliminarActivoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EliminarActivoResponse")
    @WebResult(name = "EliminarActivoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase eliminarActivo(

        @WebParam(name = "meActivo", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEActivo meActivo
    );

    @WebMethod(operationName = "GuardarInformacionMicroempresa", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarInformacionMicroempresa")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarInformacionMicroempresa", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GuardarInformacionMicroempresaResponse")
    @RequestWrapper(localName = "GuardarInformacionMicroempresa", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GuardarInformacionMicroempresa")
    @ResponseWrapper(localName = "GuardarInformacionMicroempresaResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GuardarInformacionMicroempresaResponse")
    @WebResult(name = "GuardarInformacionMicroempresaResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase guardarInformacionMicroempresa(

        @WebParam(name = "meInformacionMicroempresa", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEInformacionMicroempresa meInformacionMicroempresa
    );

    @WebMethod(operationName = "ActualizarPasivosDesdeBuro", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarPasivosDesdeBuro")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarPasivosDesdeBuro", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarPasivosDesdeBuroResponse")
    @RequestWrapper(localName = "ActualizarPasivosDesdeBuro", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarPasivosDesdeBuro")
    @ResponseWrapper(localName = "ActualizarPasivosDesdeBuroResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarPasivosDesdeBuroResponse")
    @WebResult(name = "ActualizarPasivosDesdeBuroResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarPasivosDesdeBuro(

        @WebParam(name = "mePasivos", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEPasivos mePasivos
    );

    @WebMethod(operationName = "ValidarAprobacionFlujoRelacionadosPep", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarAprobacionFlujoRelacionadosPep")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarAprobacionFlujoRelacionadosPep", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ValidarAprobacionFlujoRelacionadosPepResponse")
    @RequestWrapper(localName = "ValidarAprobacionFlujoRelacionadosPep", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ValidarAprobacionFlujoRelacionadosPep")
    @ResponseWrapper(localName = "ValidarAprobacionFlujoRelacionadosPepResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ValidarAprobacionFlujoRelacionadosPepResponse")
    @WebResult(name = "ValidarAprobacionFlujoRelacionadosPepResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase validarAprobacionFlujoRelacionadosPep(

        @WebParam(name = "meClientePep", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultasCliente meClientePep
    );

    @WebMethod(operationName = "CrearCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearClienteResponse")
    @RequestWrapper(localName = "CrearCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearCliente")
    @ResponseWrapper(localName = "CrearClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearClienteResponse")
    @WebResult(name = "CrearClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSCreacionCliente crearCliente(

        @WebParam(name = "meCreacionClientes", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MECreacionCliente meCreacionClientes
    );

    @WebMethod(operationName = "CrearDireccionCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearDireccionCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearDireccionCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/CrearDireccionClienteResponse")
    @RequestWrapper(localName = "CrearDireccionCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearDireccionCliente")
    @ResponseWrapper(localName = "CrearDireccionClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.CrearDireccionClienteResponse")
    @WebResult(name = "CrearDireccionClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase crearDireccionCliente(

        @WebParam(name = "meCreacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEDireccion meCreacion
    );

    @WebMethod(operationName = "GenerarFormularioRegistroRelacionadosPep", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GenerarFormularioRegistroRelacionadosPep")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GenerarFormularioRegistroRelacionadosPep", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/GenerarFormularioRegistroRelacionadosPepResponse")
    @RequestWrapper(localName = "GenerarFormularioRegistroRelacionadosPep", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GenerarFormularioRegistroRelacionadosPep")
    @ResponseWrapper(localName = "GenerarFormularioRegistroRelacionadosPepResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GenerarFormularioRegistroRelacionadosPepResponse")
    @WebResult(name = "GenerarFormularioRegistroRelacionadosPepResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSArchivo generarFormularioRegistroRelacionadosPep(

        @WebParam(name = "meClientePep", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultasCliente meClientePep
    );

    @WebMethod(operationName = "EnviarNotificacionCodigoSeguridad", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EnviarNotificacionCodigoSeguridad")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EnviarNotificacionCodigoSeguridad", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EnviarNotificacionCodigoSeguridadResponse")
    @RequestWrapper(localName = "EnviarNotificacionCodigoSeguridad", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EnviarNotificacionCodigoSeguridad")
    @ResponseWrapper(localName = "EnviarNotificacionCodigoSeguridadResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EnviarNotificacionCodigoSeguridadResponse")
    @WebResult(name = "EnviarNotificacionCodigoSeguridadResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase enviarNotificacionCodigoSeguridad(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEDatosCodigoSeguridad meConsulta
    );

    @WebMethod(operationName = "EliminarAccionistaAdministrador", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarAccionistaAdministrador")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarAccionistaAdministrador", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/EliminarAccionistaAdministradorResponse")
    @RequestWrapper(localName = "EliminarAccionistaAdministrador", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EliminarAccionistaAdministrador")
    @ResponseWrapper(localName = "EliminarAccionistaAdministradorResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.EliminarAccionistaAdministradorResponse")
    @WebResult(name = "EliminarAccionistaAdministradorResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase eliminarAccionistaAdministrador(

        @WebParam(name = "meAccionistaAdministrador", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEAccionistaAdministrador meAccionistaAdministrador
    );

    @WebMethod(operationName = "ActualizarDatosContacto", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarDatosContacto")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarDatosContacto", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarDatosContactoResponse")
    @RequestWrapper(localName = "ActualizarDatosContacto", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarDatosContacto")
    @ResponseWrapper(localName = "ActualizarDatosContactoResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarDatosContactoResponse")
    @WebResult(name = "ActualizarDatosContactoResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSDatosContacto actualizarDatosContacto(

        @WebParam(name = "meEntrada", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEDatosContacto meEntrada
    );

    @WebMethod(operationName = "ActualizarFormularioOrigenFondos", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarFormularioOrigenFondos")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarFormularioOrigenFondos", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarFormularioOrigenFondosResponse")
    @RequestWrapper(localName = "ActualizarFormularioOrigenFondos", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarFormularioOrigenFondos")
    @ResponseWrapper(localName = "ActualizarFormularioOrigenFondosResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarFormularioOrigenFondosResponse")
    @WebResult(name = "ActualizarFormularioOrigenFondosResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarFormularioOrigenFondos(

        @WebParam(name = "meFormulario", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEFormularioOrigenFondos meFormulario
    );

    @WebMethod(operationName = "RegistrarAutorizacionUsoDatosPersonales", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarAutorizacionUsoDatosPersonales")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarAutorizacionUsoDatosPersonales", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/RegistrarAutorizacionUsoDatosPersonalesResponse")
    @RequestWrapper(localName = "RegistrarAutorizacionUsoDatosPersonales", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.RegistrarAutorizacionUsoDatosPersonales")
    @ResponseWrapper(localName = "RegistrarAutorizacionUsoDatosPersonalesResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.RegistrarAutorizacionUsoDatosPersonalesResponse")
    @WebResult(name = "RegistrarAutorizacionUsoDatosPersonalesResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSArchivo registrarAutorizacionUsoDatosPersonales(

        @WebParam(name = "meUsoDatosPersonales", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEUsoDatosPersonales meUsoDatosPersonales
    );

    @WebMethod(operationName = "ConsultarFormulariosOrigenFondosPendientes", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarFormulariosOrigenFondosPendientes")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarFormulariosOrigenFondosPendientes", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ConsultarFormulariosOrigenFondosPendientesResponse")
    @RequestWrapper(localName = "ConsultarFormulariosOrigenFondosPendientes", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarFormulariosOrigenFondosPendientes")
    @ResponseWrapper(localName = "ConsultarFormulariosOrigenFondosPendientesResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarFormulariosOrigenFondosPendientesResponse")
    @WebResult(name = "ConsultarFormulariosOrigenFondosPendientesResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultaOrigenFondos consultarFormulariosOrigenFondosPendientes(

        @WebParam(name = "meConsulta", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEIdentificacion meConsulta
    );

    @WebMethod(operationName = "ActualizarEmailCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarEmailCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarEmailCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosClientes/ActualizarEmailClienteResponse")
    @RequestWrapper(localName = "ActualizarEmailCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarEmailCliente")
    @ResponseWrapper(localName = "ActualizarEmailClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ActualizarEmailClienteResponse")
    @WebResult(name = "ActualizarEmailClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase actualizarEmailCliente(

        @WebParam(name = "meDatosCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioclientes.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MeDatosCliente meDatosCliente
    );
}
