package servicioclientes.externalservices.web.corebanking.denarius;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-08-04T10:22:02.197-05:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "ServiciosClientes",
                  wsdlLocation = "file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir12554626392060342364.tmp/ServiciosClientes_1.wsdl",
                  targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
@HandlerChain(file = "Interceptor.xml")
public class ServiciosClientes extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("Denarius.CoreBanking.Web.ExternalServices", "ServiciosClientes");
    public final static QName WSHttpBindingIServiciosClientes = new QName("Denarius.CoreBanking.Web.ExternalServices", "WSHttpBinding_IServiciosClientes");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir12554626392060342364.tmp/ServiciosClientes_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiciosClientes.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir12554626392060342364.tmp/ServiciosClientes_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiciosClientes(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiciosClientes(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosClientes() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiciosClientes(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiciosClientes(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiciosClientes(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IServiciosClientes
     */
    @WebEndpoint(name = "WSHttpBinding_IServiciosClientes")
    public IServiciosClientes getWSHttpBindingIServiciosClientes() {
        return super.getPort(WSHttpBindingIServiciosClientes, IServiciosClientes.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiciosClientes
     */
    @WebEndpoint(name = "WSHttpBinding_IServiciosClientes")
    public IServiciosClientes getWSHttpBindingIServiciosClientes(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIServiciosClientes, IServiciosClientes.class, features);
    }

}
