application:
  title: Integrador Inversiones
  version: 1.0

server:
  port: 8081
  
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    async:
      request-timeout: 2500