package serviciocuentas.externalservices.web.corebanking.denarius;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-08-10T10:09:09.633-05:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "ServiciosCuentas",
                  wsdlLocation = "file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir5299823499069749247.tmp/ServiciosCuentas_1.wsdl",
                  targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
@HandlerChain(file = "Interceptor.xml")
public class ServiciosCuentas extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("Denarius.CoreBanking.Web.ExternalServices", "ServiciosCuentas");
    public final static QName WSHttpBindingIServiciosCuentas = new QName("Denarius.CoreBanking.Web.ExternalServices", "WSHttpBinding_IServiciosCuentas");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir5299823499069749247.tmp/ServiciosCuentas_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiciosCuentas.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir5299823499069749247.tmp/ServiciosCuentas_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiciosCuentas(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiciosCuentas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosCuentas() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiciosCuentas(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiciosCuentas(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiciosCuentas(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IServiciosCuentas
     */
    @WebEndpoint(name = "WSHttpBinding_IServiciosCuentas")
    public IServiciosCuentas getWSHttpBindingIServiciosCuentas() {
        return super.getPort(WSHttpBindingIServiciosCuentas, IServiciosCuentas.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiciosCuentas
     */
    @WebEndpoint(name = "WSHttpBinding_IServiciosCuentas")
    public IServiciosCuentas getWSHttpBindingIServiciosCuentas(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIServiciosCuentas, IServiciosCuentas.class, features);
    }

}
