package servicioinversiones.externalservices.web.corebanking.denarius;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-08-14T13:57:55.852-05:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "ServiciosInversiones",
                  wsdlLocation = "file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir6154794376160318883.tmp/ServiciosInversiones_1.wsdl",
                  targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
@HandlerChain(file = "Interceptor.xml")
public class ServiciosInversiones extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("Denarius.CoreBanking.Web.ExternalServices", "ServiciosInversiones");
    public final static QName WSHttpBindingIServiciosInversiones = new QName("Denarius.CoreBanking.Web.ExternalServices", "WSHttpBinding_IServiciosInversiones");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir6154794376160318883.tmp/ServiciosInversiones_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiciosInversiones.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir6154794376160318883.tmp/ServiciosInversiones_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiciosInversiones(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiciosInversiones(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosInversiones() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiciosInversiones(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiciosInversiones(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiciosInversiones(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IServiciosInversiones
     */
    @WebEndpoint(name = "WSHttpBinding_IServiciosInversiones")
    public IServiciosInversiones getWSHttpBindingIServiciosInversiones() {
        return super.getPort(WSHttpBindingIServiciosInversiones, IServiciosInversiones.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiciosInversiones
     */
    @WebEndpoint(name = "WSHttpBinding_IServiciosInversiones")
    public IServiciosInversiones getWSHttpBindingIServiciosInversiones(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIServiciosInversiones, IServiciosInversiones.class, features);
    }

}
