package servicioinversiones.externalservices.web.corebanking.denarius;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-08-14T13:57:55.802-05:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", name = "IServiciosInversiones")
@XmlSeeAlso({servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.ObjectFactory.class, servicioinversiones.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web.ObjectFactory.class})
public interface IServiciosInversiones {

    @WebMethod(operationName = "SimularInversionCliente", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/SimularInversionCliente")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/SimularInversionCliente", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/SimularInversionClienteResponse")
    @RequestWrapper(localName = "SimularInversionCliente", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.SimularInversionCliente")
    @ResponseWrapper(localName = "SimularInversionClienteResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.SimularInversionClienteResponse")
    @WebResult(name = "SimularInversionClienteResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSDatosInversionCliente simularInversionCliente(

        @WebParam(name = "meSimulacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MESimulacionInversionCliente meSimulacion
    );

    @WebMethod(operationName = "IngresarCancelacionRenovacionInversion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/IngresarCancelacionRenovacionInversion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/IngresarCancelacionRenovacionInversion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/IngresarCancelacionRenovacionInversionResponse")
    @RequestWrapper(localName = "IngresarCancelacionRenovacionInversion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.IngresarCancelacionRenovacionInversion")
    @ResponseWrapper(localName = "IngresarCancelacionRenovacionInversionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.IngresarCancelacionRenovacionInversionResponse")
    @WebResult(name = "IngresarCancelacionRenovacionInversionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSDatosInversionCliente ingresarCancelacionRenovacionInversion(

        @WebParam(name = "meInstruccion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEInstruccionInversion meInstruccion
    );

    @WebMethod(operationName = "ConsultarSaldosCuentas", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/ConsultarSaldosCuentas")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/ConsultarSaldosCuentas", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/ConsultarSaldosCuentasResponse")
    @RequestWrapper(localName = "ConsultarSaldosCuentas", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarSaldosCuentas")
    @ResponseWrapper(localName = "ConsultarSaldosCuentasResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarSaldosCuentasResponse")
    @WebResult(name = "ConsultarSaldosCuentasResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSConsultasInversion consultarSaldosCuentas(

        @WebParam(name = "meInversiones", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web.MEIdentificacionCliente meInversiones
    );

    @WebMethod(operationName = "SimularInversion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/SimularInversion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/SimularInversion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/SimularInversionResponse")
    @RequestWrapper(localName = "SimularInversion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.SimularInversion")
    @ResponseWrapper(localName = "SimularInversionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.SimularInversionResponse")
    @WebResult(name = "SimularInversionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSSimulacionInversion simularInversion(

        @WebParam(name = "meSimulacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MESimulacionInversion meSimulacion
    );

    @WebMethod(operationName = "AperturarInversionSolicitud", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/AperturarInversionSolicitud")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/AperturarInversionSolicitud", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/AperturarInversionSolicitudResponse")
    @RequestWrapper(localName = "AperturarInversionSolicitud", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.AperturarInversionSolicitud")
    @ResponseWrapper(localName = "AperturarInversionSolicitudResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.AperturarInversionSolicitudResponse")
    @WebResult(name = "AperturarInversionSolicitudResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSDatosInversion aperturarInversionSolicitud(

        @WebParam(name = "meApertura", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEAperturaInversionSolicitud meApertura
    );

    @WebMethod(operationName = "GenerarCertificadosCaptacionesRenovadas", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/GenerarCertificadosCaptacionesRenovadas")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/GenerarCertificadosCaptacionesRenovadas", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/GenerarCertificadosCaptacionesRenovadasResponse")
    @RequestWrapper(localName = "GenerarCertificadosCaptacionesRenovadas", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GenerarCertificadosCaptacionesRenovadas")
    @ResponseWrapper(localName = "GenerarCertificadosCaptacionesRenovadasResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.GenerarCertificadosCaptacionesRenovadasResponse")
    @WebResult(name = "GenerarCertificadosCaptacionesRenovadasResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeSalidaBase generarCertificadosCaptacionesRenovadas(

        @WebParam(name = "meLiquidacion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web.MensajeEntradaBase meLiquidacion
    );

    @WebMethod(operationName = "AperturarInversion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/AperturarInversion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/AperturarInversion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/AperturarInversionResponse")
    @RequestWrapper(localName = "AperturarInversion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.AperturarInversion")
    @ResponseWrapper(localName = "AperturarInversionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.AperturarInversionResponse")
    @WebResult(name = "AperturarInversionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSDatosInversionCliente aperturarInversion(

        @WebParam(name = "meApertura", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEAperturaInversion meApertura
    );

    @WebMethod(operationName = "ConsultarDetalleInversion", action = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/ConsultarDetalleInversion")
    @Action(input = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/ConsultarDetalleInversion", output = "Denarius.CoreBanking.Web.ExternalServices/IServiciosInversiones/ConsultarDetalleInversionResponse")
    @RequestWrapper(localName = "ConsultarDetalleInversion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarDetalleInversion")
    @ResponseWrapper(localName = "ConsultarDetalleInversionResponse", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices", className = "externalservices.web.corebanking.denarius.ConsultarDetalleInversionResponse")
    @WebResult(name = "ConsultarDetalleInversionResult", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
    public servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MSDetalleInversion consultarDetalleInversion(

        @WebParam(name = "meInversion", targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
        servicioinversiones.org.datacontract.schemas._2004._07.denariuscorebanking_web_externalservices.MEConsultaProducto meInversion
    );
}
