package serviciocreditos.externalservices.web.corebanking.denarius;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-08-14T12:09:02.495-05:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "ServiciosCreditos",
                  wsdlLocation = "file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir11758202466595082812.tmp/ServiciosCreditos_1.wsdl",
                  targetNamespace = "Denarius.CoreBanking.Web.ExternalServices")
@HandlerChain(file = "Interceptor.xml")
public class ServiciosCreditos extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("Denarius.CoreBanking.Web.ExternalServices", "ServiciosCreditos");
    public final static QName WSHttpBindingIServiciosCreditos = new QName("Denarius.CoreBanking.Web.ExternalServices", "WSHttpBinding_IServiciosCreditos");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir11758202466595082812.tmp/ServiciosCreditos_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiciosCreditos.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/EVERA~1.COO/AppData/Local/Temp/tempdir11758202466595082812.tmp/ServiciosCreditos_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiciosCreditos(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiciosCreditos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosCreditos() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiciosCreditos(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiciosCreditos(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiciosCreditos(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IServiciosCreditos
     */
    @WebEndpoint(name = "WSHttpBinding_IServiciosCreditos")
    public IServiciosCreditos getWSHttpBindingIServiciosCreditos() {
        return super.getPort(WSHttpBindingIServiciosCreditos, IServiciosCreditos.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiciosCreditos
     */
    @WebEndpoint(name = "WSHttpBinding_IServiciosCreditos")
    public IServiciosCreditos getWSHttpBindingIServiciosCreditos(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIServiciosCreditos, IServiciosCreditos.class, features);
    }

}
